### ISSUE TITLE
create_customer not posting cvv

### ISSUE THREAD

**Issue by timeverts** [fatzebra/PHP-Library#6]
According to https://docs.pmnts.io/display/DOC/Customers, posting to /customers requires that the 'card' data also contain an element for the card cvv.

FatZebra::create_customer has cvv as an input parameter (and it's mandatory), but it doesn't actually get sent in the payload.

Please add 'cvv' as an element of the 'card' data in the payload.

**Comment by amasses** [comment]
Hi,

This has been fixed.
