### ISSUE TITLE
Automated tests failing

### ISSUE THREAD

**Issue by moroland** [fatzebra/PHP-Library#7]
https://travis-ci.org/fatzebra/PHP-Library/jobs/74786539

There was 1 failure:
1) GatewayTest::test_invalid_refund
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Exception caught in application - error ID: 7eb7c8f010925d8efa02853d13f3b1b2. Please contact Payment support for more details'
+'Original transaction is required'

My local test have this error too:
There was 1 error:

1) GatewayTest::test_fetch_refund
InvalidArgumentException: Reference is required

/app/FatZebra.class.php:184
/app/test/gateway_tests.php:129

**Comment by amasses** [comment]
Thanks for the notification. I've fixed this up and your tests should run properly now if you pull the latest rev.
